### ISSUE TITLE
ERRORR results for ENDF-VIII n + Ca40 are unphysical

### ISSUE THREAD

**Issue by mattooca** [njoy/NJOY2016#111]
ERRORR produces very high uncertainties from the new ENDF-VIII Ca40 evaluation. Per discussion with the evaluator (M. Pigni at ORNL), it sounds like these may be due to an NJOY processing problem rather than a problem in the evaluation.

Ca40 provides MF=32 for LRF=7 resonances, including (n,p) and (n,a) channels. AMPX results are very different from NJOY, showing ~10-20% uncertainty for thermal capture where NJOY reports ~10000%.

Processing was done with njoy 2016.44 (master branch, updated today). Input file: [xnjoy.input.txt](https://github.com/njoy/NJOY2016/files/2558422/xnjoy.input.txt)

![mt1_xsc](https://user-images.githubusercontent.com/5640239/48147625-c5b06680-e285-11e8-8c78-9aa1da77a666.png)
![mt2_xsc](https://user-images.githubusercontent.com/5640239/48147626-c648fd00-e285-11e8-9c94-76094c5aa5bd.png)
![mt102_xsc](https://user-images.githubusercontent.com/5640239/48147627-c648fd00-e285-11e8-8ec9-223afdd2b338.png)
![mt600_xsc](https://user-images.githubusercontent.com/5640239/48147628-c648fd00-e285-11e8-8faf-cd864592bb56.png)
![mt800_xsc](https://user-images.githubusercontent.com/5640239/48147629-c648fd00-e285-11e8-98b1-a03788c2bff3.png)

**Comment by jlconlin** [comment]
Thanks @mattooca We'll take a look at this.

**Comment by whaeck** [comment]
We already encountered an issue with this evaluation, see #60. I am looking at it right now.
