### ISSUE TITLE
libnjoy.so error

### ISSUE THREAD

**Issue by JanFrybort** [njoy/NJOY2016#12]
I tried building NJOY 2016 in Ubuntu 16.10, gcc version 6.2.0. Compiling seems to go without problems, but while trying to run njoy, there is an error: error while loading shared libraries: libnjoy.so: cannot map zero-fill pages.

**Comment by apmccartney** [comment]
Hello @JanFrybort . Welcome to github. =)

Does your full error message look something like this?
`libnjoy.so: cannot map zero-fill pages: cannot allocate memory`

**Comment by JanFrybort** [comment]
Actually, the "cannot allocate memory" part is missing, but it was the problem. I tried it in a virtual machine with just 1 GB memory. It worked when I increased memory to 2 GB. Thank you for helping me.
