### ISSUE TITLE
Problem processing new endf files for IRDFF-II issued by the IAEA

### ISSUE THREAD

**Issue by lgreenwood10** [njoy/NJOY2016#124]
The new version of the IRDFF-II files created at the IAEA Nuclear Data Section include natural element reactions to multiple activation products such as natural iron to Cr-51, Mn-54, Mn-56, etc.  NJOY cannot properly process these files for the cross sections or covariances.  Users have to break up the IRDFF endf file into separate parts for each activation product to get NJOY to work,  Skiip Khaler has a workaound but it is not acceptable since it uses illegal LFS values to process mf8 and mf10 files.  No such fix (legal or not) has been able to process mf40 files.  If the endf files are split into separate files for each activation product, then NJOY works correctly.  Contacts at the IAEA are Andrej Trkov, Roberto Capote Noy, and Daniel Aldama.

**Comment by jlconlin** [comment]
@lgreenwood10 Thanks for making an issue!

Can you please add some NJOY input files to this pull request as well as the necessary ENDF files? We can’t try this out without them. You should be able to drag and drop those files onto this issue. I think you had those files in the email communication that you sent previously.

**Comment by lgreenwood10** [comment]
Will do

Larry Greenwood
Laboratory Fellow
Pacific Northwest National Laboratory
509-375-5301

**Comment by lgreenwood10** [comment]
I added the input file (in_FeIRDFF2.,txt) and Feendf.txt file for the natural iron case that won't process with NJOY.  If you truncate the endf file to have only one of the 4 activation products then it works correctly,
Larry
[in_FeIRDFF2.txt](https://github.com/njoy/NJOY2016/files/2946918/in_FeIRDFF2.txt)

[Fenatendf.txt](https://github.com/njoy/NJOY2016/files/2946924/Fenatendf.txt)

**Comment by lgreenwood10** [comment]
Done

Larry Greenwood
Laboratory Fellow
Pacific Northwest National Laboratory
509-375-5301

**Comment by kahlerac** [comment]
This issue arises because until recently the ENDF-6 format did not allow natural element reactions in file 10.  Since the CSEWG community has now relaxed this restriction we need to expand NJOY2016's capability so that it properly recognizes and processes this revised format.  A previously developed patch for NJOY2012 will soon be ported and tested for NJOY2016.

**Comment by lgreenwood10** [comment]
Thanks, Skip!
This will be very helpful for processing IRDFF-II files.

Larry Greenwood
Laboratory Fellow
Pacific Northwest National Laboratory
509-375-5301

**Comment by lgreenwood10** [comment]
Thanks!


Larry Greenwood
Laboratory Fellow
Pacific Northwest National Laboratory
509-375-5301

**Comment by lgreenwood10** [comment]
I am currently trying to process the entire IRDFFII library for use with my STAYSL_PNNL computer code.  I am using NJOY2016.78    The cross sections discussed above for MF10 multi-isotope entries appear to be processing (although I have not yet confirmed this with testing).  However, I cannot get the mfcov=40 covariances to process correctly for these cases.  I am asking if anyone has been able to process these covariances correctly?  If so, I would like to discuss and hopefully fix the problems I am having.  If not, then this issue needs to be addressed.  Thanks!
