### ISSUE TITLE
Test problem 2 issue

### ISSUE THREAD

**Issue by xzhiwen** [njoy/NJOY2016#13]
As I am attempting to build an x64 executable for Windows using Intel Fortran 14.0.3.202, I uncovered an issue in running Test Problem 2. It uses t404 tape that is ENDF/B-IV data. When I enforce /fpe:0, i.e., disallow floating point exceptions, the run aborted with the following message:

```
 njoy 2016.9   28Feb17                                       03/09/17 00:05:27
 *****************************************************************************

 moder...                                                                 0.0s

 reconr...                                                                0.1s

 ---message from emerge---nonpositive elastic cross sections found.

 broadr...                                                                0.2s
forrtl: error (65): floating invalid
Image              PC                Routine            Line        Source
njoy2016_00.exe    000000013FCF1E66  ENDF_mp_CONTIO             64  endf.f90
njoy2016_00.exe    000000013FC8C7EC  BROADM_mp_BROADR          260  broadr.f90
njoy2016_00.exe    000000013FFE529F  MAIN__                    199  main.f90
njoy2016_00.exe    00000001400816F6  Unknown               Unknown  Unknown
njoy2016_00.exe    000000014008208C  Unknown               Unknown  Unknown
kernel32.dll       00000000774A59CD  Unknown               Unknown  Unknown
ntdll.dll          00000000775DA561  Unknown               Unknown  Unknown
```
After some investigations, I found that in the broadr module, the third `CONTIO` call reads the text line and causes the `nint` failed to convert a large float (~1E162) back to integer.

Later, I removed the /fpe:0 option, and successfully ran this problem with the same pendf output. Dr. Skip found some logic in reconr to determine the ENDF format version, which might be used in broadr to fix this problem.

**Comment by jlconlin** [comment]
@xzhiwen Have you tried this lately? We have made many changes over the last couple of months. We think your problem has been corrected.

**Comment by xzhiwen** [comment]
@jlconlin Thank you for the reminder. I synchronized to the most recent master branch, and re-compiled with /fpe:0 option in Intel compiler. The test problem 2 now works fine. This issue should be closed now.
