### ISSUE TITLE
Poto-Atomic  Data

### ISSUE THREAD

**Issue by elijahritz89** [njoy/NJOY2016#150]
I've generated the Photo-Atomic cross section library (ACER), but unfortunately the fluorescence and heating data are incorrect and the output shows NAN for these data.
This program is executed by NJOY2016.55.
Could anyone help me to solve the issue?

**Comment by whaeck** [comment]
In order to properly diagnose this issue, we'll need an example input file and ENDF file (or at least the location where we can download this ENDF file).

Best regards,
Wim

**Comment by elijahritz89** [comment]
Thank you Wim for your answer, fortunately I could solve the issue.

Wishes, Elijah
