### ISSUE TITLE
Exclude MT3 from ACE processing?

### ISSUE THREAD

**Issue by whaeck** [njoy/NJOY2016#151]
Some evaluations such as Ni59 from ENDF/B-VII.1 (which was taken from JEFF, which was in turn based on an old JEF 2.2 evaluation) appear to have the redundant MT3 reaction in it. In the case of Ni59, MT3 appears to be equal to MT1 (I checked the first and last value of the cross section).

Should we consider adding a check in NJOY2016 to avoid MT3 to be added to the ACE file. See 28059.80c as an example.

**Comment by paulromano** [comment]
When a photon yield is given as a multiplicity (as opposed to a photon production cross section), I think the neutron reaction cross section needs to remain in the file. In this file, there is photon production associated with MT=3, so my guess is that removing the neutron reaction cross section would break photon production. The evaluation does appear to be broken though in the sense that MT=1 is not the sum of MT=2 and MT=3 (as required by ENDF-102).
