### ISSUE TITLE
New IAEA photonuclear data library does not process

### ISSUE THREAD

**Issue by whaeck** [njoy/NJOY2016#156]
The IAEA is currently working on a new photonuclear data library and the standard processing through NJOY2016 fails to process the file.

There appear to be a number of differences between these new files and what was already available through ENDF/B-VIII.0:
- the new files have considerably more reactions available (including a total cross section which does not seem to be present in the older files), this includes all inelastic levels and individual levels of cross sections like n,p, n,2n, etc.

The following MF6 sections appear to be processed normally (these are the cases encountered for most of the ENDF/B-VIII.0 files):
- Any MF6 subsection using LAW=1, LANG=2 (kalbach-mann systematics). This is translated in a LAW=44 in the ACE file.
- Any MF6 subsection using LAW=1, LANG=1 (Legendre coefficients) with NA=0 (isotropic angular distributions) for every incident energy. This is translated in a LAW=4 in the ACE file.
- Any MF6 subsection using LAW=2, LANG=0 (Legendre coefficients). The Legendre polynomial expansion is transformed into a pdf/cdf before being included in the ACE file. Once this is transformed, the coding shares a processing path with the next one.
- Any MF6 subsection using LAW=2, LANG=12 or 14 (tabulated P(mu)).

The new files appear to use MF6 subsections using LAW=1, LANG=1 (Legendre coefficients) with NA!=0 (coefficients will be given) for some or all incident energies. This would translated in a LAW=4 in the ACE file and the angular distributions for the secondary particle is lost.

In addition, the vanilla NJOY2016 fails to process the new files due to the presence of the total cross section. 

This description will be updated with additional information.

**Comment by whaeck** [comment]
Andrej Trkov provided a upn style update to fix the processing issue and to resolve an issue with the locators:
```
*/
*ident upnea156
*/ acepn - A. Trkov, Processing of photonuclear files
*/         WARNING - IMPORTANT - Please note that with the current
*/                   coding particle energy distributions are
*/                   stored under LAW=4, which implies isotropic
*/                   distribution, even when they are given in MF=6
*/                   with as an expanded Legendre series.
*/                 - On processing of files with explicit channel
*/                   representation the ACER module produces no
*/                   messages, but the ACE file is incomplete and
*/                   fails the second ACER run for file checking.
*/                 - Packing of the data for LAW=4 is incorrect (nex).
*/                   It implies the presence of angular data, which
*/                   is in the ENDF file, but is not entered for LAW=4.
*/                 - The z-limits for the plot were not calculated
*/                   correctly for distributions with pseudo-threshold.
*d acepn.66
   integer,parameter::mmax=800
*i acepn.69
   character(60)::strng
*d acepn.150
      if (mfd.ge.3.and.(mtd.eq.2.or.mtd.gt.4)) then
*d acepn.244
         if (mth.ne.1.and.mth.ne.3.and.mth.ne.4) then
*d acepn.326
            if (mth.ge. 50 .and. mth.le. 91) nneut=nneut+1
*d acepn.536,537
               else if (law.eq.0) then
                  write(strng,'(''recoil'',i6,'' in MT'',I4)')izap,mth
                  call mess('acephn','no heating info for ',strng)
               !--this law is not currently handled
               else
                  write(strng,'(''particle '',i5,'' law'',I4)')izap,law
                  call mess('acephn','file 6 law not coded for ',strng)
*d acepn.1469
!                          nex=nex+2+(2*na+3)*ng  ! Original coding
                           nex=nex+2+(     3)*ng
*d acepn.3181
                     !--Skip first two point that may be pseudo-threshold
                     do j=3,nn
*/
```

**Comment by whaeck** [comment]
Updates are being put in the feature/pn-iaea branch.

I have added two tests for photonuclear data from ENDF/B-VIII.0 (U235 and Bi209) to test the vanilla NJOY2016 and ENDF/B-VIII.0 capabilities as tests 56 and 57. These tests are essentially added to ensure that anything we do for correcting this issue does not break previous processing.

In a previous update (see issue https://github.com/njoy/NJOY2016/issues/130 and https://github.com/njoy/NJOY2016/pull/147), the output routine for the continuous energy ACE file was rewritten using subroutines to reduce the number of lines of code as well as to add verification of the locators used in the ACE file. This has now been applied to photonuclear data as well. 
The the xss array is now defined in acecm.f90 and no longer in every ace*.f90 file. All functions common to this feature (all ```write_*``` functions, the ```avance_to_locator``` function and the ```typen``` function) are now defined in acecm.f90 as well. From now on, this will help us detect issues in the locators and detect coding errors.

**Comment by nasim1367** [comment]
Hello

I tried to generate  ACE-format library of JENDL/PD-2016 (photonuclear reactions) using the NJOY-2016 code but failed, Why?
What should I do to convert this library to an ACE file?

Thank you

**Comment by whaeck** [comment]
Hi @nasim1367 

It appears that your question is not related to this issue (i.e. processing the new IAEA photonuclear data library, which actually requires changes to NJOY2016). In order to keep this issue clean, we would like to ask you to open a separate issue on your problem. In addition, when you open that issue, we would also like you to give us more information on how you processed the library (e.g. provide an input file that you used) and describe the problem you're encountering (e.g. information on a crash, or a failure by MCNP to read the resulting ACE file, etc.).

Once you have opened a new issue and provided us with the necessary information, we'll be able to assist you.

Best regards,
Wim

**Comment by nasim1367** [comment]
Hi Dear Wim

Thanks for your explanation
I created a new issue
I hope the information and attachments clearly explain my problem
please guide me
Thanks a lot
