### ISSUE TITLE
Identifier and issues

### ISSUE THREAD

**Issue by jchsublet** [njoy/NJOY2016#158]
It would be of some use to let trusty user know which issues (bug or enhancement) has been solved in, by the latest master release, been as I wrote
 
   character(8),public::vers='2016.56'
   character(8),public::vday='24Jan20'

And may be which branches are available for testing, or you want to keep that to the few

**Comment by jlconlin** [comment]
Thanks for the comment @jchsublet. You can see this information in the [Release Notes](https://github.com/njoy/NJOY2016/blob/master/ReleaseNotes.md). 

The updates that are available in the different branches changes on a regular basis and would be challenging to keep that updated. We do invite a few people to test those branches—as you are well aware.

**Comment by whaeck** [comment]
I just updated the releases for NJOY2016 to add 2016.56. I should have done that when we pulled in that fix from the start. My apologies for this delay.

I'll update the release notes as well.

**Comment by whaeck** [comment]
The release notes already contain 2016.56. I must have done something right :-)

**Comment by jlconlin** [comment]
> The release notes already contain 2016.56. I must have done something right :-)

Don't let this go to your head!

**Comment by jchsublet** [comment]
Apologies, I did not previously "see" the release notes. Having said that is there a way to flag the issues in that case #130 as done, achieved, checked ? as the issuer I'll happily do this now, in doing so recognising your impressive skill and commitment to serve a community that do not always let know how your efforts are appreciated

**Comment by jlconlin** [comment]
You can always go and look at the issue. At the top is an indication of the status of the issue. When a Pull Request is accepted that fixes an issue, we need to make sure to state that the issue has been resolved. 

<img width="1021" alt="Screen Shot 2020-04-22 at 7 56 41 AM" src="https://user-images.githubusercontent.com/1275437/79990887-d69b6a80-846e-11ea-9ecd-24202906ba91.png">

**Comment by jchsublet** [comment]
@jlconlin indeed, I could have should I have noticed the "38 open 40 closed" tabs !! which now I have !! Thank you
