### ISSUE TITLE
NaN's at "random" in gfortran builds

### ISSUE THREAD

**Issue by brown170** [njoy/NJOY2016#16]
So, I know I've been pestering you by email about this, but I've got a big problem with NaN's appearing both in PURR probability tables and when generating postscript plots.  Skip tracked down one source of NaN's to gfortran's treatment of if-then clauses.  Let me explain....

Take for example this psuedo-code:
if (expression a) and (expression b) then
... do something
endif

if (expression a) evaluates to FALSE, then there is no reason to attempt to execute (expression b).  Most compilers (and Python too) operate this way.  Not so gfortran.  Apparently it attempts to execute (expression b) before ever evaluating the "and" part.  The interpretation of it-then statements with "and" in the middle is not fully specified in the FORTRAN specifications.

OK, so what happens in gfortran is that it does (expression b), somehow gets confused and does the "do something", resulting in the use of uninitialized variables.  These are often array indices. When the code attempts to access bogus memory, it results in memory leaks. 

Memory leaks can lead to very bizarre and non-deterministic code execution, leading to to the symptoms I see.  In the case Skip found, an if-then in BROADR lead to weird behavior in PURR.

Compiling with bounds checking helps (that's how Skip found the last leak).  Better would be to just run NJOY2016 with gfortran through Valgrind.

**Comment by apmccartney** [comment]
That's surprising. I wrote up a short program to see for myself.

```fortran
function left()
  implicit none
  logical :: left
  write(*,*) "left was executed"
  left = .false.
end function left

function right()
  implicit none
  logical :: right
  write(*,*) "right was executed"
  right = .true.
end function right

program main
  implicit none
  logical :: left, right
  if ( left() .and. right() ) then
    write(*,*) "Entered body"
  endif
end program main
```

Given the behavior you describe, I would expect the output of this program to be either

```
 left was executed
 right was executed
```

or

```
 left was executed
 right was executed
 Entered body
```

However, when I compile with gfortran locally, the output is 

```
 left was executed
```

which seems to indicate gfortran 6.3 (which I believe you were using on your Mac) is using a short-circuited logical `and` (as is standard specified by C and company). The output can be verified [online](https://ideone.com/8pwoqd). Do you have a minimum, complete, verifiable example demonstrating the behavior?

**Comment by brown170** [comment]
This what skip described to me, so maybe I didn't get the details exactly right.   Probably the best thing to do is find the change he made to broadr. He suspected the confused logic is used elsewhere.  Even if I don't have the source of the NaNs right, Val grind is something worth trying out
Dave

Sent from my iPhone

On Apr 9, 2017, at 12:55 AM, Austin McCartney <notifications@github.com<mailto:notifications@github.com>> wrote:


That's surprising. I wrote up a short program to see for myself.

function left()
  implicit none
  logical :: left
  write(*,*) "left was executed"
  left = .false.
end function left

function right()
  implicit none
  logical :: right
  write(*,*) "right was executed"
  right = .true.
end function right

program main
  implicit none
  logical :: left, right
  if ( left() .and. right() ) then
    write(*,*) "Entered body"
  endif
end program main

Given the behavior you describe, I would expect the output of this program to be either

 left was executed
 right was executed


or

 left was executed
 right was executed
 Entered body


However, when I compile with gfortran locally, the output is

 left was executed


which seems to indicate gfortran 6.3 (which I believe you were using on your Mac) is using a short-circuited logical and (as is standard specified by C and company). The output can be verified online<https://ideone.com/8pwoqd>. Do you have a minimum, complete, verifiable example demonstrating the behavior?

**Comment by paulromano** [comment]
These two tidbits from the Fortran 2008 standard give some insight:

Section 7.1.5.4.2, clause 1:
> Once the interpretation of a logical intrinsic operation is established, the processor may evaluate any other expression that is logically equivalent, provided that the integrity of parentheses in any expression is not violated.

Section 7.1.7, clause 1:
> It is not necessary for a processor to evaluate all of the operands of an expression, or to evaluate entirely each operand, if the value of the expression can be determined otherwise.

So, the first clause indicates that Fortran does not require left-to-right evaluation and thus as a programmer you should not rely on short circuit behavior. But, the second clause says that a compiler writer is free to implement short circuit evaluation if they so desire, i.e., don't rely on every operand to be evaluated.

For what it's worth, I've recently been running into these same issues with NaNs a lot as well. It seems to be sensitive to compiler version and optimization flags used.

**Comment by apmccartney** [comment]
Thank you for the pointers to the relevant part of the standard @paulromano.

**Comment by brown170** [comment]
Between Paul's recent patch and Skip's previous patches, all the NaN's seem to have gone!
Yea!
