### ISSUE TITLE
MODER doesn't work for Atomic Relaxation Data (NSUB = 6)

### ISSUE THREAD

**Issue by MAS-OUD** [njoy/NJOY2016#162]
It appears that `MODER` doesn't work for Atomic Relaxation Data (NSUB = 6). In the following, tape 20 is the Atomic Relaxation Data from the ENDF/B-VIII.0 library:
```
moder
20 -21 /
```
or
```
moder
1 -21 /
'mat = 100' /
20 100 /
0 /
```
both fail with the error
```
***error in moder***conversion not coded for mf= 28
```

**Comment by whaeck** [comment]
Hmm, interesting. I'll have a look to see what's going on. Thanks for pointing this out.

**Comment by whaeck** [comment]
Little update on this one:

I have a working branch with an updated moder (fix/moder) but I am seeing issues when using a binary photoatomic file together with a binary atomic relaxation file in ACER. I still need to figure out what's up with that. In ASCII mode, all works normally.

**Comment by jchsublet** [comment]
@whaeck a though from the past, there is absolutely no reasons been physical or numerical to parse atomic relaxation or charged particles evaluations through moder as the ASCII forms of those are more than sufficient for useful application. MODER BCD means binary coded data and was never intended to covers all forms of the nuclear data NJOY's module can handle. It is in fact pretty bold, inutile, likely to have unforeseen consequence to do so.

**Comment by whaeck** [comment]
The remaining issue was a missing repoz(in) call, see the fix/moder branch. It now works properly, both binary and ascii input tapes for ACER give the same ACE file.
