### ISSUE TITLE
Reference outputs are not used during make test

### ISSUE THREAD

**Issue by vivian-salino** [njoy/NJOY2016#171]
Hello, everybody,

I am very intrigued by the fact that obtained outputs and reference outputs are not compared during `make test`. This surprising fact can be reproduced very simply by running the test battery _without error_ with the following commands:
```git clone https://github.com/njoy/NJOY2016.git
cd NJOY2016
cmake .
make
cd tests
rm -f */referenceOutput
make test
```

Maybe is it on purpose? But if so, why are the reference outputs kept at all?

**Comment by whaeck** [comment]
Salut Vivian

You are correct, the outputs are not used in the tests, only tapes are compared. You'll see that in the more recent tests that we've added over the years, none of the outputs are saved.

We probably should clean up those outputs at some point but it's not really a pressing issue.

Best regards,
Wim

**Comment by vivian-salino** [comment]
Merci Wim !

Bonne journée et au plaisir 😃
