### ISSUE TITLE
NaN values keep appearing in some charged particle ACE files

### ISSUE THREAD

**Issue by whaeck** [njoy/NJOY2016#173]
For a new d+He3 evaluation, the ACE file produced by NJOY2016 still has a few NaN values appearing in it.

The following input and ENDF file reproduce the issue:
[input.txt](https://github.com/njoy/NJOY2016/files/5029333/input.txt)
[d-002_He_003.endf.txt](https://github.com/njoy/NJOY2016/files/5029338/d-002_He_003.endf.txt)

**Comment by whaeck** [comment]
This problem was due to an array index overflow in acecpe. It was fixed in #172

**Comment by jchsublet** [comment]
Still time to make the above evaluation more in line with a more realistic knowledge of cross-section and not a numerical exercise : 

        42          6        226          5                       225 3600    3
 1.000000+2 1.1551-117 2.000000+2 3.03977-82 3.000000+2 1.35488-66 225 3600    4
 4.000000+2 2.75847-57 5.000000+2 6.04874-51 6.000000+2 2.84953-46 225 3600    5
 7.000000+2 1.20594-42 8.000000+2 1.00138-39 9.000000+2 2.60358-37 225 3600    6
 1.000000+3 2.85824-35 2.000000+3 2.83175-24 3.000000+3 1.91099-19 225 3600    7

Really?

**Comment by whaeck** [comment]
I agree, and I told the evaluators that they can probably change the lower energy limit. It's work in progress but it did point out a potential problem in NJOY so I'll keep it as a test ;-)
