### ISSUE TITLE
As small inconsistency, but in acepn

### ISSUE THREAD

**Issue by jchsublet** [njoy/NJOY2016#175]
acepn.f90:   integer,parameter::mmax=80
plotr.f90:   integer,parameter::mmax=20000   !same in plotr and viewr
viewr.f90:   integer,parameter::mmax=20000   !same in plotr and viewr

As ENDF files get more 'complicated' I would argue the 80 may not suffice

**Comment by whaeck** [comment]
Salut Jean-Christophe

The feature/pn-iaea branch updated this value in acepn.f90 to 1000. We can bump it up to 20000 to be in line with what viewr and plotr use (if the meaning of the variable is the same of course). I'll have to get back to the MCNP folks here at LANL to see how we can get the new ACE files produced by this branch accepted by MCNP. If changing this variable is urgent, I can make the change in a separate fix.

**Comment by jchsublet** [comment]
Ah ! I did not get that, and would agree with your better choice of 1000 instead of 20000 in acepn. But there is no urgency
