### ISSUE TITLE
ERRORR doesn't close files when using the 999 option

### ISSUE THREAD

**Issue by jlconlin** [njoy/NJOY2016#192]
There is an undocumented(?) feature of ERRORR where you can add MF=33 data to an existing Tape. This is done by setting the first argument on Card1 to be `999` (see [Test20](https://www.njoy21.io/NJOY2016/testDescription.html#test-problem-20)). In this case, ERRORR reads in data, and writes data to the file, but it doesn't close the files. 

When run all by itself, everything works fine because Fortran will close the file automatically. However, when running mixed with modern components in NJOY21, the files are not completed and written to disk before the next module is run.

**Comment by whaeck** [comment]
Fixed in #196
