### ISSUE TITLE
 Typo in acecm but right (n,Xn) count

### ISSUE THREAD

**Issue by jchsublet** [njoy/NJOY2016#195]
From ENDF/B-VIII.0 O016 acer check output, but also 40 others targets in ENDF/B-VIII.0 and many TENDL-2019

       reaction descriptors
       --------------------

       reaction        mt     tyr      lsig      land      ldlw              emin           emax              q
       --------        --     ---      ----      ----      ----      ------------   ------------   ------------
****
       (n,2np)         41      -2      2079        -1     50814      2.440886E+01   1.500000E+02  -2.296090E+01
       (n,2np)         44      -1      2218        -1     53140      2.374349E+01   1.500000E+02  -2.233500E+01
****

In acecm.f90 line 32

>     '(n,2np)   ','(n,3np)   ','(n,x)     ','(n,2np)   ','(n,npa)   ',& 
>     '(n,2np)   ','(n,3np)   ','(n,x)     ','(n,n2p)   ','(n,npa)   ',& ==> better
        41           42           43           44          45 

In the runes bible:

mt = 41 (z,2np)
mt = 44 (z,n2p) 

But then mth.eq.44 logic in acefc.f90 seems OK, n=1 and not 2 as for mth.eq.41

Plotr, covr, matxsr, groupr allocation logic for that matter seems right

**Comment by whaeck** [comment]
Fixed in #200
