### ISSUE TITLE
Adding NJOY to the Fortran Package Index

### ISSUE THREAD

**Issue by certik** [njoy/NJOY2016#216]
I just submitted an entry for NJOY:

https://github.com/fortran-lang/fortran-lang.org/pull/303

Let me know if the one line description and the title is ok or if you want to change it.

**Comment by whaeck** [comment]
@certik I forgot to reply to you. I checked the description, and it is perfect for me. No need to make changes.

**Comment by certik** [comment]
Perfect, thanks!
