### ISSUE TITLE
Issue processing Zr in ZrH2 (new evaluation for ENDF/B-VIII.1)

### ISSUE THREAD

**Issue by paulromano** [njoy/NJOY2016#218]
When trying to process the new ENDF/B [Zr in ZrH2 evaluation](https://git.nndc.bnl.gov/endf/library/thermal_scatt/-/blob/phase1/tsl-ZrinZrH2.endf), I'm running into the following error:
```
 njoy 2016.64  24May21                                       08/30/21 21:58:16
 *****************************************************************************

 reconr...                                                                0.0s

 broadr...                                                                0.5s
      293.6 deg                                                           0.6s
      400.0 deg                                                           0.9s
      500.0 deg                                                           1.3s
      600.0 deg                                                           1.7s
      700.0 deg                                                           2.1s
      800.0 deg                                                           2.6s
     1000.0 deg                                                           3.0s
     1200.0 deg                                                           3.4s

 thermr...                                                                3.8s

 wrote thermal data for temp = 2.9360E+02                                 7.5s

 wrote thermal data for temp = 4.0000E+02                                11.2s

 wrote thermal data for temp = 5.0000E+02                                15.0s

 wrote thermal data for temp = 6.0000E+02                                19.1s

 wrote thermal data for temp = 7.0000E+02                                23.1s

 wrote thermal data for temp = 8.0000E+02                                27.5s

 wrote thermal data for temp = 1.0000E+03                                31.5s

 wrote thermal data for temp = 1.2000E+03                                35.3s

 thermr...                                                               35.3s

 ***error in rdelas***too much elastic data
                      increase na
 
STOP 77
corrupted size vs. prev_size
```
As the error message suggests, if I increase na (from 10,000 to 500,000) it does work. Thought I'd report this in case you guys want to consider making that a permanent change.

**Comment by whaeck** [comment]
Hi Paul,

Thanks for the heads-up, we appreciate it.

We've actually addressed this one already on the feature/mixed-elastic branch. That branch has the mixed mode elastic enabled in MODER, THERMR and ACER. One of the changes I made was to increase the value of na from 10000 to now 1 million.

I haven't finalised that branch yet since I need to finish up a few details related to plotting the ACE data. I'll also need to make some verification in GROUPR to see if that module can handle it (I assume it will). After that, we need to test the new ACE file in MCNP6 (there is an MCNP6 version now that should accept the new format).

I haven't looked at the evaluation you linked to, but is this a mixed mode one, or just a single mode like in ENDF/B-VIII.0?

Best regards,
Wim

**Comment by paulromano** [comment]
Ah, great to hear. Having na=1 million will solve it for sure. It looks like this particular evaluation has LHTR=1, so just a single mode one. In fact, I don't see any mixed mode evaluations yet in the thermal scattering library, so I guess the ones where it is being used haven't been submitted.

**Comment by whaeck** [comment]
The only one I currently have is Be in LiBe. That was the one included in the format proposal for ENDF.

I'd love to get a few more to be able to assess the impact on some benchmark cases.

**Comment by marquezj** [comment]
We have many mixed elastic evaluations here if you want to used them as test:

https://github.com/highness-eu/NJOY-NCrystal-Library/tree/master/mixed_elastic

I am bit busy these days, but when I find time I will run the official implementation on them.

**Comment by paulromano** [comment]
Confirmed this is fixed on `master` at this point
