### ISSUE TITLE
"Segmentation fault - invalid memory reference" in acer

### ISSUE THREAD

**Issue by brown170** [njoy/NJOY2016#22]
When I run with NJOY2016, I get a seg. fault in the acer module.

I attached my example.  This only happens with 249Cf from ENDF/B-VIII.0beta4 (unchanged since VII.1).  

[Archive.zip](https://github.com/njoy/NJOY2016/files/984492/Archive.zip)

**Comment by paulromano** [comment]
I ran your input file on my system and it ran to completion with no seg faults. Are you using the current master branch?

**Comment by brown170** [comment]
Yep, commit 6ab7a84c2648661bbc7a0a9a03547066481ab351.  Does this on my production linux box running gcc7.1 on RHEL 6.8 as well as my laptop running gcc 6.3.0 on macOS 10.12.4.

**Comment by jlconlin** [comment]
I ran the same problem on my Mac using fortran 6.3.0. I ran in debug mode (`cmake -D CMAKE_BUILD_TYPE=Debug ../`). With that, I got a little more information than you did:

```
At line 15517 of file /.../acefc.f90
Fortran runtime error: '1001' of dimension 1 of array 'ee' above upper bound of 1000
```

I'm not quite sure what the problem is right now. Trying to work through this.

**Comment by brown170** [comment]
thnx

**Comment by jlconlin** [comment]
@brown170 We made a change and have pushed it to the master branch. It should fix your problem.

**Comment by brown170** [comment]
it works!
