### ISSUE TITLE
New ENDF/VIII beta 4 thermal scattering law MTe/MTi numbers?

### ISSUE THREAD

**Issue by veeshy** [njoy/NJOY2016#24]
I'm trying to make ACE format thermal scattering data for moderators not listed in the NJOY manual. Specifically, when using THERMR and mtref entry is required on card 2. A list of MT #'s are provided in Table 4 of the NJOY2016 manual, but they do not have new moderating materials in it (specifically, S in SiC and C in SiC in my case but others too). Are these "magic" numbers within NJOY so more MT's need to be added, or are they ENDF standards that I should be able to find somewhere?

**Comment by paulromano** [comment]
My own experience is that as long as your mti in ACER matches whatever you put for mtref in THERMR, it works ok. If thermal elastic data is present, then you should set `mte = mti + 1`. I'm also curious to hear an official answer from one of the NJOY developers though.

**Comment by veeshy** [comment]
Ah, this does seem to work, thanks! I tried with various combinations of mte #'s and the final final diff's were blank. I'm going to close this but a dev should re-open if this thread is incorrect.

**Comment by paulromano** [comment]
The manual seems to imply that the mtref value may be consequential if you're using MATXSR. In any event, better guidance in the manual seems to be warranted.
