### ISSUE TITLE
NJOY package for conda-forge?

### ISSUE THREAD

**Issue by paulromano** [njoy/NJOY2016#240]
@whaeck @nathangibson14 As you know, OpenMC relies on NJOY for generating ACE files, which are then converted into our own HDF5 format, so NJOY is essentially an optional dependency for OpenMC. We have a [conda-forge package](https://github.com/conda-forge/openmc-feedstock/) for OpenMC that is popular with users, but when they install from there they don't get NJOY automatically. I'd like to setup a conda-forge package for NJOY so that I can list that as runtime dependency for OpenMC, which means anyone installing OpenMC from conda-forge would automatically get NJOY as well. Before I do that though, I wanted to check with you guys to make sure you're OK with it. In particular, I would probably base the package off NJOY2016 rather than NJOY21 since NJOY2016 continues to be the "production" version, as best as I can tell.

**Comment by nathangibson14** [comment]
Hey @paulromano, NJOY2016 is indeed the easier option to use right now, and there are no practical differences between the two with regards to processing.  So agreed, NJOY2016 makes sense.

No qualms with the conda-forge package for your purposes.  If we pursue deployment with those sorts of utilities on our side later, we can revisit, but we don't have anything in the works right now.

**Comment by kkiesling** [comment]
Excellent- I will get started on a conda forge recipe and post it here when I have something that works and/or the conda-forge PR open. I will probably reach out again to get a list of people who want to be maintainers too.

**Comment by kkiesling** [comment]
I have the start of a conda forge package ready [here](https://github.com/conda-forge/staged-recipes/pull/18547). When this is merged by conda-forge, our feedstock will be available.

@nathangibson14 or any other developers- would you like me to add you as a maintainer for the conda-forge feedstock?

**Comment by kkiesling** [comment]
@nathangibson14 and @whaeck - not sure if you saw my comment on the conda forge PR [here](https://github.com/conda-forge/staged-recipes/pull/18547#issuecomment-1087659705), but you will both need to consent via comment on that PR to being maintainers before the conda forge package can be accepted.

**Comment by kkiesling** [comment]
[NJOY2016](https://github.com/conda-forge/njoy2016-feedstock) has officially been added to conda forge! 🎉
