### ISSUE TITLE
ptleg2 error on ACER

### ISSUE THREAD

**Issue by cvbalderas** [njoy/NJOY2016#247]
Hello.

I'm new to NJOY and while processing multiple materials from ENDF/B-VII.1 for multiple temperatures I encountered this error:
 
---message from ptleg2---negative probs found
                            60 for mt=  2 e= 2.000E+07

 ---message from ptleg2---negative probs found
                           270 for mt=  2 e= 2.200E+07

It is the same error from #164, but I encountered it for multiple materials such as B-10, U-238, Pu-238, etc.. From #164 it was related to the evaluation data and got resolved with [errata](https://www.nndc.bnl.gov/endf/b8.0/errata.html). However I cannot check the link since it's giving me:
![image](https://user-images.githubusercontent.com/58495186/168972704-2de471da-f18d-4c87-a07a-7582db6b3e3a.png)

Here is the sample input file for U-235 (given as example from the NJOY training held last 2021):
moder
 20 -21
reconr
 -21 -22 /
 'A PENDF for U-238 from ENDF/B-VII.1' /
 9237 / 
 0.001 /
 0 / 
broadr
 -21 -22 -30              /
 9237 5 0 1               /
 0.001                    / 
 293.6 600 900 1200 2500  /
 0                        /
heatr
 -21 -30 -40 45 /
 9237 7 /
 302 303 304 318 402 443 444 /
purr
 -21 -40 -50 /
 9237 5 1 20 64 1 0 /
 293.6 600 900 1200 2500 /
 1E10 /
 0 /
gaspr
 -21 -50 -60
acer
 -21 -60 0 70 75                    / Card1
 1 1 1 .10 0                        / Card2 
 'U-238 @ 293.6K from ENDF/B-VII.1' / Card3
 9237 293.6                         / Card5
 / Card6---all defaults
 / Card7---all defaults
acer
  0 70 81 91 92                     / Card1
  7 1                               / Card2
 'U-238 @ 293.6K from ENDF/B-VII.1' / Card3
viewr
  81 86
.
.
.
stop

**Comment by whaeck** [comment]
So the link in issue 164 was bad, I edited it.
