### ISSUE TITLE
photoatomic and atomic relax data problem?

### ISSUE THREAD

**Issue by luohao0925** [njoy/NJOY2016#249]
The problem is that NJOY produces the photoatomic ace data for U element. After that, the output ace file does not involve the shell and the sub-shell data (NXS[5] and NXS[7] are equal to zero). I'm using the newest version of NJOY2016 and ENDF-B-VIII.0 library. I also tried the ENDF-B-VII.1, and the same thing happened.

my input is [input.txt](https://github.com/njoy/NJOY2016/files/9010141/input.txt), and the output is [tape27.txt](https://github.com/njoy/NJOY2016/files/9010145/tape27.txt)

**Comment by whaeck** [comment]
After looking through the source code, it seems that NJOY2016 does not add the shell and sub-shell data to the ACE file even though the format specifications mention this data. I will look though older versions of NJOY to see if it ever added this data. It is possible the data was added to the existing ACE files in the past by another tool.

**Comment by whaeck** [comment]
None of the older NJOY versions seem to add the electron shell data.

If this data needs to be added for your purposes, we do have other tools available that would help do that.

**Comment by luohao0925** [comment]
Your reply really helps! Thank you very much
