### ISSUE TITLE
problem regarding installation. all tests fail

### ISSUE THREAD

**Issue by khurrumsaleem** [njoy/NJOY2016#26]
Hello,

First of all i want to say sorry to create an issue for this as i don't know where else to seek help. Secondly, thanks to all the developers. You are doing a marvelous job. 

Coming to the issue, i am trying to install njoy2016 on ubuntu 16.04 LTS. i have tried using gfortran 5.4.0 to install. There are lot of warnings during installation regarding equalities and inequalities. then after compilation when i run the test, all of them fail. Can you please guide me regarding this. @jlconlin

**Comment by khurrumsaleem** [comment]
Hello,

Turns out the issue was python2 and python3. issue resolved by setting up python3 environment. now all the tests are passing.

**Comment by jlconlin** [comment]
I'm sorry for the slow response to this issue. Glad you were able to find a resolution.
