### ISSUE TITLE
acer fails to properly print (iopt=7) a pre-existing dosimetry ace file

### ISSUE THREAD

**Issue by kahlerac** [njoy/NJOY2016#303]
Tried to print (acer/iopt=7) an ACE file from the IAEA's IRDFF-II library but got all zeroes for the energy, xsec.  It's a one line patch in subroutine dosfix to make sure we've read the full xss array prior to printing.

**Comment by whaeck** [comment]
I think we fixed this in 2016.71 or 2016.72 so we can close this.
