### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Vincent-Hugo** [njoy/NJOY2016#323]
Hello!
When I try to process some isotopes (U-235,U-238, Pu,...) in ENDF/B-VIII.0 .
It emerges:
------------------------------------------------------------
 moder...                                                                 0.0s
At line 852 of file D:\src\endf.f90 (unit = 50, file = 'tape50')
Fortran runtime error: End of file
------------------------------------------------------------
Could please explain to me and fix.

**Comment by whaeck** [comment]
There could be multiple reasons why this is happening but I would need an input file and an evaluation for which this happens.

Can you send me your input file so I can have a look? Thanks.

**Comment by Vincent-Hugo** [comment]
I merely used MODER MODULE  like this:
-------------------------------------------
moder
20 -21
stop
-------------------------------------------
it worked for other isotope.

**Comment by Vincent-Hugo** [comment]
I now using NJOY 2016.73 and MinGW
