### ISSUE TITLE
Problem processing DT ENDF/B-VIII.1b3 into ACE format

### ISSUE THREAD

**Issue by ocabellos** [njoy/NJOY2016#332]
Hi,

Using the following input, NJOY2016.74 fails to process the ENDF/B-VIII.1b3 evaluated deuteron induced reaction for H003 (tritium) into ACE format.

The error message is:
"***error in change***Undefined law for dlwh block:   0"

=========================
moder                                          /
20 -21                                         /
moder                                          /
20 -22                                         /
acer                                           / generate ACE file
-21 -22 0 25 26                                / NENDF, NPENDF, NGEND, NACE, NDIR
1 0 1 .81                                      / IOPT, IPRINT, ITYPE, SUFF
' H003 NJOY2016.74 - ENDFB81b3 for deuterons' / HK
131 0.                                         / MAT, tempr
1 1                                            / NEWFOR, IOPP
                                               /
acer                                           / check ace file
0 25 27 25 26                                  / NENDF, NPENDF, NGEND, NACE, NDIR
7 1 1 -1                                       / IOPT, IPRINT, ITYPE, SUFF
' H003 NJOY2016.74 - ENDFB81b3 for deuterons' / HK
viewr                                          / generate postscript file
27 28                                          / infile, PS output file
stop                                           / The END
=================================

**Comment by ax990712** [comment]
Hello!

I adopted the input provided above and brought its output into mcnp6, but encountered the following problem:

When the incident deuterium ion energy is low (1mev), there is no neutron count. When the energy is high (10mev), there is a count, but it is not concentrated at 14mev

How can I solve it? Looking forward to your reply. Thank you very much!
