### ISSUE TITLE
NJOY 2016 version number and date

### ISSUE THREAD

**Issue by whaeck** [njoy/NJOY2016#36]
We should figure out what to do with vers.f90. We have not changed this since the last updates.

**Comment by apmccartney** [comment]
I would like to deprecate and eventually remove it altogether.

**Comment by whaeck** [comment]
I agree.

On another issue: you ... are ... on ... vacation ! Close that browser right now, young man ;-)

**Comment by jlconlin** [comment]
We need to be very cautious about this. There are *many* who rely upon the version number and the date to know how current their version of NJOY is. They may not be able to update their copy as often as we do. 

I’m not saying we shouldn’t, we just need to make sure this is the right thing to do and ensure our customers understand how they can know what version they are running and when it was current.

**Comment by apmccartney** [comment]
![](https://smhttp-ssl-5891.nexcesscdn.net/media/catalog/product/cache/1/image/1800x/6b9ffbf72458f4fd2d3cb995d92e8889/d/o/dowhatiwant_newthumb.png)

**Comment by apmccartney** [comment]
> We need to be very cautious about this. There are many who rely upon the version number and the date to know how current their version of NJOY is. They may not be able to update their copy as often as we do.
>
>I’m not saying we shouldn’t, we just need to make sure this is the right thing to do and ensure our customers understand how they can know what version they are running and when it was current.

Agreed but we can have CMake generate this file automatically if we want to preserve that feature

**Comment by jlconlin** [comment]
I’m certainly not opposed to having CMake do this for us. That’s much better than doing this by hand.

**Comment by whaeck** [comment]
Even though we do it manually, we have restarted putting in version numbers since December of last year.
