### ISSUE TITLE
Make file difficult to generate

### ISSUE THREAD

**Issue by Aspire1Inspire2** [njoy/NJOY2016#41]
Why python script? The environment is hard to setup and not easy to run.
Just give us a makefile, let us do whatever modification for our own system. Life is simple and easy in this way.

I ended up writing my own Makefile myself from scratch. The python script does not help at all.

**Comment by Aspire1Inspire2** [comment]
FC=ifort
OPTS= -O

OBJS= mainio.o locale.o util.o endf.o mathm.o phys.o samm.o \
    acecm.o acepa.o aceth.o errorr.o covr.o graph.o leapr.o \
    matxsr.o powr.o resxsr.o unresr.o viewr.o acedo.o acepn.o \
    broadr.o dtfr.o gaminr.o groupr.o mixr.o purr.o \
    wimsr.o acefc.o acer.o ccccr.o gaspr.o heatr.o \
    moder.o plotr.o reconr.o thermr.o vers.o main.o

xnjoy: ${OBJS}
        ${FC} ${OPTS} -o $@ ${OBJS}

%.o: %.f90
        ${FC} ${OPTS} -c $<

clean:
        rm -rf *.o *.mod xnjoy

**Comment by Aspire1Inspire2** [comment]
Please just post this makefile, let whoever has a problem running the python script modify it by themselves.

**Comment by apmccartney** [comment]
The [instructions](https://njoy.github.io/Build/) never call for users to invoke a python script. 

```
mkdir bin
cd bin
cmake ../
make
```

Let CMake generate the Make file.
