### ISSUE TITLE
Should the user be able to change the `ismooth` parameter? 

### ISSUE THREAD

**Issue by jlconlin** [njoy/NJOY2016#46]
The `ismooth` parameter is used in both ACER and GROUPR to provide smoothing for MF=6 distributions. Currently, the value of `ismooth` is hard-coded into the ACER and GROUPR module. There is a suggestion that this parameter should be specified by the user.

The verbiage in [`acefc.f90`](https://github.com/njoy/NJOY2016/blob/master/src/acefc.f90#L89) is:
```
   ! set ismooth to 1 to cause extension of mf6 cm distributions
   ! to lower energies using a sqrt(E) shape, to extend delayed
   ! neutron distributions as sqrt(E) to lower energies, and to
   ! add additional points above 10 Mev to some fission spectra
   ! assuming an exponential shape.  otherwise, use ismooth=0.
   ! NOTE:  ismooth=0 is the default value in njoy99.
```

and in [`groupr.f90`](https://github.com/njoy/NJOY2016/blob/master/src/groupr.f90#L94)
```
   ! smoothing option
   ! set ismooth to 1 to enable sqrt(e) smoothing for
   ! mf6 cm emission spectra at low energies and for
   ! histogram delayed neutron spectra at low energies.
   ! set ismooth to 2 to get the changed distribution
   ! printed out on the output listing.
```

**Comment by whaeck** [comment]
The upn files provided by Daniel Lopez-Aldama of the IAEA/NDS addresses this issue for ACER. This is now available in feature/upn-iaea with a new test (test 28) that tests the defaults. I still have to check GROUPR.

**Comment by whaeck** [comment]
GROUPR has an ismooth parameter that can take the values 0,1 or 2. I have played around with the ismooth=2 option which should print the modified spectra to the output file but I only seem to get blank lines when I do that. As a result, I have taken out the ismooth=2 option altogether. ismooth is now the next parameter after iprint on card 2.

**Comment by whaeck** [comment]
This is now in the master branch so the issue can be closed.
