### ISSUE TITLE
Minimum GNU version

### ISSUE THREAD

**Issue by paulromano** [njoy/NJOY2016#47]
I noticed that in CMakeLists.txt, the minimum GNU version is set to 5.1. I was curious as to what the particular reason for this is. If I remove that line, I'm able to compile fine with earlier versions of gfortran, e.g., 4.8. Should I expect something to go wrong if I do?

**Comment by jlconlin** [comment]
You shouldn't see any problems if you use gcc <5.1. I believe @apmccartney required 5.1 because of some capabilities with reporting a stack trace when something failed. He can provide more detailed information.

**Comment by paulromano** [comment]
@jlconlin @apmccartney Would you guys entertain a pull request removing that restriction? As part of OpenMC's Python API, we have some bindings to NJOY for generating ACE files and the native HDF5 format that OpenMC relies on for its data (you can see a [notebook here](http://openmc.readthedocs.io/en/latest/examples/nuclear-data.html#Generating-data-from-NJOY) if you're curious what it looks like). I'm trying to add unit tests for our bindings which means getting NJOY installed on Travis CI. I know that it's possible to access a more recent gcc on Travis CI (as you guys do) but we are still supporting gfortran 4.8+ for OpenMC, so I'd like to avoid updating gcc if possible.

Keep up the great work -- love what you guys are doing with NJOY!

**Comment by apmccartney** [comment]
Hey Paul!

Let me give gfortran 4.8 a try across our test matrix. Assuming the test
board is a wall of green, I'm happy to change the requirement.
Alternatively, maybe we could publish a binary for you guys to install
during your travis configuration?

**Comment by paulromano** [comment]
Thanks! Binaries would be great in general, but not absolutely necessary. As is, the entire clone/cmake/make process for NJOY is only like 30 seconds or something so not a big deal.
