### ISSUE TITLE
All the tests in Cygwin Failed.

### ISSUE THREAD

**Issue by suhailak** [njoy/NJOY2016#48]
Hi
This may be a trivial issue for the experts here. Kindly help
I am able to compile the NJOY 2016 in Cygwin environment in a Windows 7 machine. But all the tests do fail. Besides what is the way to run the NJOY from command line in Cygwin? Is it to be run only through Python Script? Which directory can i find this script?
Thanks

**Comment by jlconlin** [comment]
Thanks for the report. The latest version of NJOY2016 should run all the tests without failure if you are using the gcc compiler. If you have a different compiler, then differences are to be expected. 

As far as running NJOY, you can run the executable directly; you should not run through the Python script. After compiling, you can do `make install` to install the executable in standard places.

**Comment by suhailak** [comment]
Thank you @jlconlin. I think i am using latest gcc & gfortan compilers. I am on leave for some time. I will update all the versions etc to you when i join the work and will discuss further. 
Thanks and Cheers

**Comment by suhailak** [comment]
I am using the gcc and gfortran versions 6.4.0 in the Cygwin environment. The file njoy.exe is built smoothly and can be seen in /bin directory. Following is the output of "make test" command
******************************************************************************
Running tests...
Test project /cygdrive/d/NJOY2016/bin
      Start  1: Test01
 1/23 Test  #1: Test01 ...........................***Failed    1.80 sec
      Start  2: Test02
 2/23 Test  #2: Test02 ...........................***Failed    0.41 sec
      Start  3: Test03
 3/23 Test  #3: Test03 ...........................***Failed    0.39 sec
      Start  4: Test04
 4/23 Test  #4: Test04 ...........................***Failed    0.38 sec
      Start  5: Test05
 5/23 Test  #5: Test05 ...........................***Failed    0.37 sec
      Start  6: Test06
 6/23 Test  #6: Test06 ...........................***Failed    0.39 sec
      Start  7: Test07
 7/23 Test  #7: Test07 ...........................***Failed    0.54 sec
      Start  8: Test08
 8/23 Test  #8: Test08 ...........................***Failed    0.38 sec
      Start  9: Test09
 9/23 Test  #9: Test09 ...........................***Failed    0.37 sec
      Start 10: Test10
10/23 Test #10: Test10 ...........................***Failed    0.38 sec
      Start 11: Test11
11/23 Test #11: Test11 ...........................***Failed    0.38 sec
      Start 12: Test12
12/23 Test #12: Test12 ...........................***Failed    0.37 sec
      Start 13: Test13
13/23 Test #13: Test13 ...........................***Failed    0.36 sec
      Start 14: Test14
14/23 Test #14: Test14 ...........................***Failed    0.38 sec
      Start 15: Test15
15/23 Test #15: Test15 ...........................***Failed    0.37 sec
      Start 16: Test16
16/23 Test #16: Test16 ...........................***Failed    0.40 sec
      Start 17: Test17
17/23 Test #17: Test17 ...........................***Failed    0.79 sec
      Start 18: Test18
18/23 Test #18: Test18 ...........................***Failed    0.37 sec
      Start 19: Test19
19/23 Test #19: Test19 ...........................***Failed    0.38 sec
      Start 20: Test20
20/23 Test #20: Test20 ...........................***Failed    1.49 sec
      Start 21: Test21
21/23 Test #21: Test21 ...........................***Failed    1.34 sec
      Start 22: Test22
22/23 Test #22: Test22 ...........................***Failed    0.39 sec
      Start 23: Test23
23/23 Test #23: Test23 ...........................***Failed    0.37 sec

0% tests passed, 23 tests failed out of 23

Total Test time (real) =  13.10 sec

The following tests FAILED:
          1 - Test01 (Failed)
          2 - Test02 (Failed)
          3 - Test03 (Failed)
          4 - Test04 (Failed)
          5 - Test05 (Failed)
          6 - Test06 (Failed)
          7 - Test07 (Failed)
          8 - Test08 (Failed)
          9 - Test09 (Failed)
         10 - Test10 (Failed)
         11 - Test11 (Failed)
         12 - Test12 (Failed)
         13 - Test13 (Failed)
         14 - Test14 (Failed)
         15 - Test15 (Failed)
         16 - Test16 (Failed)
         17 - Test17 (Failed)
         18 - Test18 (Failed)
         19 - Test19 (Failed)
         20 - Test20 (Failed)
         21 - Test21 (Failed)
         22 - Test22 (Failed)
         23 - Test23 (Failed)
Errors while running CTest
make: *** [Makefile:84: test] Error 8
******************************************************************************
Also when i run njoy.exe at command line, it gives the message  "bus error".
Kindly help.
Thanks

**Comment by jlconlin** [comment]
Can you please execute the following and let us know what is produced:

```
ctest -V -R Test01
```

**Comment by suhailak** [comment]
Thanks for the response. Following is the output you asked for
*****************************************************************
UpdateCTestConfiguration  from :/Path on Cygwin/NJOY2016/DartConfiguration.tcl
UpdateCTestConfiguration  from :/Path on Cygwin/NJOY2016/DartConfiguration.tcl
Test project /Path on Cygwin/NJOY2016
Constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
No tests were found!!!
************************************************************************************

**Comment by suhailak** [comment]
The output from the above command is:
*********************************************************************
UpdateCTestConfiguration  from :/Path on Cygwin/NJOY2016/bin/DartConfiguration.tcl
UpdateCTestConfiguration  from :/Path on Cygwin/NJOY2016/bin/DartConfiguration.tcl
Test project /Path on Cygwin/NJOY2016/bin
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: Test01

1: Test command: /usr/bin/python "../execute.py"
1: Test timeout computed to be: 9.99988e+06
1:       1 [main] python2.7 4400 child_info_fork::abort: address space needed by 'cygz.dll' (0x610000) is already occupied
1: Traceback (most recent call last):
1:   File "../execute.py", line 18, in <module>
1:     child = subprocess.Popen(njoy, stdin=i, stdout=o, stderr=e)
1:   File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
1:     errread, errwrite)
1:   File "/usr/lib/python2.7/subprocess.py", line 917, in _execute_child
1:     self.pid = os.fork()
1: OSError: [Errno 11] Resource temporarily unavailable
1/1 Test #1: Test01 ...........................***Failed    5.09 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   6.82 sec

The following tests FAILED:
          1 - Test01 (Failed)
Errors while running CTest
*********************************************************************************************

**Comment by jlconlin** [comment]
This looks like a problem with the configuration of your machine. A quick search on the internet indicates it may be related to a virus protection issue. This is not something wrong with NJOY.
