### ISSUE TITLE
Curious length of XSS array in ACE file

### ISSUE THREAD

**Issue by paulromano** [njoy/NJOY2016#50]
I'm trying to process [ENDF/B-VIII.0 beta6](https://ndclx4.bnl.gov/gf/project/endf/frs/?action=FrsReleaseBrowse&frs_package_id=30) using NJOY2016 and I'm running into an issue with B-10. NJOY actually runs fine and generates an ACE file, no problem. Looking at the ACE file, I see that NXS(1) is 82851 implying that the XSS array should be found over (NXS(1) + 3)/4 = 20713 lines. However, the file actually has an additional 12 lines of zeros (mix of floating point and integers) after the required 20713 lines. The end of the file looks like:
```
   2.00000000000E+00   1.00000000000E-11   2.00000000000E+01   1.00000000000E+00
   1.00000000000E+00  -2.54432100000E+00   5.78648900000E-01   3.00000000000E+00
   7.00000000000E+02   8.00000000000E+02   8.01000000000E+02   0.00000000000E+00
   0.00000000000E+00   0.00000000000E+00   0.00000000000E+00   0.00000000000E+00
   0.00000000000E+00   0.00000000000E+00   0.00000000000E+00   0.00000000000E+00
   0.00000000000E+00   0.00000000000E+00   0.00000000000E+00   0.00000000000E+00
   0.00000000000E+00   0.00000000000E+00   0.00000000000E+00   0.00000000000E+00
   0.00000000000E+00   0.00000000000E+00   0.00000000000E+00   0.00000000000E+00
   0.00000000000E+00   0.00000000000E+00   0.00000000000E+00   0.00000000000E+00
   0.00000000000E+00   0.00000000000E+00   0.00000000000E+00   0.00000000000E+00
   0.00000000000E+00   0.00000000000E+00   0.00000000000E+00   0.00000000000E+00
   0.00000000000E+00   0.00000000000E+00   0.00000000000E+00   0.00000000000E+00
   0.00000000000E+00   0.00000000000E+00   0.00000000000E+00   0.00000000000E+00
   0.00000000000E+00                   0                   0                   0
                   0                   0                   0                   0
                   0                   0                   0                   0
```
where the last value in XSS is actually 8.01e2. So, my question is -- what are all these zeros and why are they there? Is this a valid ACE file or is something wrong? The scripts that I have for parsing ACE files fail on this one in a way that I've never seen before so it makes me a little suspicious.

Here's my input deck for good measure:
```
reconr /
20 21
'ENDF/B-8.0 PENDF for   5-B - 10 '/
525 2/
0.001/ err
'ENDF/B-8.0:   5-B - 10 '/
'Processed by NJOY'/
0/
broadr /
20 21 22
525 1 0 0 0. /
0.001/ errthn
293.6
0/
heatr /
20 22 23 /
525 3 /
302 318 402 /
purr /
20 23 24 /
525 1 1 20 64 /
293.6
1.e10
0/
acer /
20 24 0 25 26
1 0 1 .01 /
'ENDF/B-8.0:   5-B - 10  at 293.6'/
525 293.6
1 1/
/
stop
```

**Comment by jlconlin** [comment]
I have not run your input deck, but I am seeing the same issue on our own processing of <sup>10</sup>B. We have run this through MCNP and don't get any noticeable problems. We are having other issues with <sup>10</sup>B, perhaps they are related. I think there is something wrong with the data, but I'm not sure what it is at the moment.

In any event, regardless of the data, NJOY should produce a valid XSS array.

**Comment by paulromano** [comment]
Ok, good to know I'm not crazy! I see @brown170's name on the file description, so let's blame him.

**Comment by paulromano** [comment]
@jlconlin Have you found out anything more about the <sup>10</sup>B issues?

**Comment by jlconlin** [comment]
@paulromano I had totally forgotten about this issue. I've been too busy getting ENDF/B-VIII.0 processed.

**Comment by paulromano** [comment]
As noted in #164, there was an error in the original VIII.0 evaluation for B10 (errata [here](https://www.nndc.bnl.gov/endf/b8.0/errata.html)). Recent updates to NJOY also cause it to produce an error with the original evaluation rather than letting it slide through with no errors (but weird values in the ACE file). The fixed B10 evaluation works just fine, so I'll go ahead and close this issue.
