### ISSUE TITLE
THERMR produces NaNs when emax parameter is too large

### ISSUE THREAD

**Issue by jlconlin** [njoy/NJOY2016#62]
An issue has been discovered where `NaN`s are produced when the `emax` parameter is too large.

In the attached input deck, the `emax` parameter is set to `10.0` and we get `NaN`s from THERMR. When that parameter is set to `5.0` then everything runs smoothly.

This input uses Fe-56 input. which is also attached. 

[input.txt](https://github.com/njoy/NJOY2016/files/1678458/input.txt)
[n-026_Fe_056.txt](https://github.com/njoy/NJOY2016/files/1678464/n-026_Fe_056.txt)

**Comment by marquezj** [comment]
A couple of weeks ago, Dan Roubtsov made me note that for free gas THERMR computes S(a,b) on a  [very limited beta grid of 9 values](https://github.com/njoy/NJOY2016/blob/476f822cddc2c4c0afa1989ff4f5f013d65b56e7/src/thermr.f90#L1796). I checked if that is related to this issue, and it is: for larger `emax` you need larger `beta` values.

Increasing the grid solves the NaNs, but changes slightly the results in THERMR and Test 1 fails (test2 11 and 24 seem to be less sensitive to this change and pass). I prepared a pull request with this if you want to test it   (#64).

(More properly, the grid should be adaptatively created from `emax` and `tempr`, but that might take longer to implement and test)

**Comment by whaeck** [comment]
Hi Ignacio,

Thank you for sharing this, it does solve the issue we encountered. Dan Roubtsov also contributed a few changes in acer related to the thermal scattering so I would propose to include your changes in that branch (you can see it as the "feature/acer-endf8" branch).

I would also like to add a test that would allow us to signal this issue in the future. I was thinking about something like:
````
if ((de/bk/temp).gt.b(30)) call mess( ... )
````
in which de is some realistic upper limit value for the energy transfer.

Best regards,
Wim

**Comment by whaeck** [comment]
This issue has been fixed in the pull request for feature/acer-endf8

njoy ;-)
