### ISSUE TITLE
Old physics constants in src/phys.f90

### ISSUE THREAD

**Issue by mattooca** [njoy/NJOY2016#9]
According to documentation, the physics constants are based on the 1989 CODATA compilation.  There are new values in the 2014 compilation  (see http://physics.nist.gov/cuu/Constants/).  I recommend updating to those.

**Comment by jlconlin** [comment]
@mattooca Should we update to the 2014 constants or use the constants recommended in the ENDF manual?

**Comment by mattooca** [comment]
Good point, should be consistent with the ENDF manual. I guess it's too late to update the recommended values there before the ENDF-VIII release, but I'd like to keep it in mind for future releases.

**Comment by jlconlin** [comment]
This was resolved in #99 and (subsequently) in #107.
